const mongoose=require('mongoose')
const userModal=mongoose.Schema({
    name:{
        type:String,
        require:true
    },
    mobile:{
        type:String,
        require:true
    },
    email:{
        type:String,
        require:true
    },
    password:{
        type:String,
        require:true
    },
    verified:{
        type:String,
        default:0
    },
    otp:{
        type:Number,
        default:0
    },
    isadmin:{
        type:String,
        default:0
    },
    cart:{
        type:Array
    },
    wishList:{
        type:Array,
    },
    address:{
        type:Array
    }
})
module.exports=mongoose.model('user',userModal)